### ISSUE TITLE
Gnome Shell Extension

### ISSUE THREAD

**Issue by milani** [omid/pcalendar#1]
Hi,

Gnome Shell 3 supports extensions now. There can be an extension for pcalendar.

**Comment by omid** [comment]
Hello,

I see, and I like to develop it!
But I don't have enough free time to research for it and develop something like pcalendar!
If you have any knowledge about JS & Clutter or at all "GNOME extension development", tell me to give access to you.

Regards.

**Comment by omid** [comment]
Hey,

I think it's done :D
https://github.com/omid/Persian-Calendar-for-Gnome-Shell
